---
- name: Add docker repository key
  tags: packages
  apt_key: url=https://get.docker.io/gpg state=present
  when: ansible_os_family == "Debian"

- name: Add docker repository
  tags: packages
  apt_repository: repo="deb http://get.docker.io/ubuntu docker main" state=present
  when: ansible_os_family == "Debian"

- name: Update package list
  tags: packages
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install packages
  tags: packages
  apt: pkg={{item}} state=present
  with_items:
  - lxc-docker
  - git
  - python-setuptools
  - lldpd
  when: ansible_os_family == "Debian"

- name: Install packages
  tags: packages
  yum: pkg={{item}} state=present
  with_items:
  - docker-io
  - git
  - python-setuptools
  - lldpd
  when: ansible_os_family == "RedHat"

- name: Install docker-py
  tags: packages
  command: easy_install docker-py

- name: Pull images
  tags: docker
  command: docker pull {{item}}
  with_items:
    - registry.docker:5000/admin
    - registry.docker:5000/mysql
    - registry.docker:5000/keystone

#- name: Clone dockerfiles
#  tags: docker
#  git: repo=https://github.com/Apsu/dockerlab-files dest={{ansible_env.HOME}}/dockerfiles update=yes
# 
#- name: List dockerfiles
#  tags: docker
#  shell: ls -d1 {{ansible_env.HOME}}/dockerfiles/*
#  register: output
# 
#- name: Build docker images
#  tags: docker
#  docker_image: path={{item}} name="dockerlab/{{item|basename}}" state=build
#  with_items: output.stdout_lines
