---
- name: Generate hosts
  tags: hosts
  hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Add node
    add_host:
      name: "{{host_prefix}}-node{{item}}"
      groups: hosts,cluster,infra
      rax_flavor: performance1-2
      ifaces:
        svc:
          iface: eth2
          ipv4: 172.20.0.{{item}}
          mask: 255.255.255.0
        iso:
          iface: eth3
    with_sequence: count={{host_count}}
