---
- name: Generate hosts
  tags: hosts
  hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Add first node
    add_host:
      name: "{{host_prefix}}-node1"
      groups: hosts,cluster,infra
      rax_flavor: performance1-2
      ifaces:
        svc:
          iface: eth2
          ipv4: 172.20.0.1
          mask: 255.255.255.0
        iso:
          iface: eth3
  - name: Add second node
    add_host:
      name: "{{host_prefix}}-node2"
      groups: hosts,cluster,infra
      rax_flavor: performance1-2
      ifaces:
        svc:
          iface: eth2
          ipv4: 172.20.0.2
          mask: 255.255.255.0
        iso:
          iface: eth3
  # - name: Add second infra host
  #   add_host:
  #     name: "{{prefix}}-infra2"
  #     groups: hosts, cluster, infra
  #     rax_flavor: performance1-2
  #     ifaces:
  #       svc:
  #         iface: eth2
  #         ipv4: 172.20.0.3
  #         mask: 255.255.255.0
  #       iso:
  #         iface: eth3
  # - name: Add compute host
  #   add_host:
  #     name: "{{prefix}}-compute1"
  #     groups: hosts, cluster, compute
  #     rax_flavor: performance1-4
  #     ifaces:
  #       svc:
  #         iface: eth2
  #         ipv4: 172.20.0.4
  #         mask: 255.255.255.0
  #       iso:
  #         iface: eth3
