---
- name: Ensure hosts exist
  tags: ensure
  local_action:
    module: rax
    name: "{{inventory_hostname}}"
    credentials: "{{rax_creds}}"
    key_name: "{{rax_keypair}}"
    networks: "{{rax_net_labels}}"
    region: "{{rax_region}}"
    flavor: "{{rax_flavor}}"
    image: "{{rax_image}}"
    disk_config: "{{rax_diskconfig}}"
    wait: yes
    state: present
  register: rax

- name: Store host access IPs
  tags: ensure
  set_fact: ansible_ssh_host={{item.accessIPv4}}
  when: item.name == inventory_hostname # Avoid dupes
  with_items: rax.instances

- name: Explicitly gather facts to check platform
  tags: packages
  setup: filter=ansible_os_family

- name: Install LSB
  tags: packages
  yum: name=redhat-lsb-core state=present
  when: ansible_os_family == "RedHat"
