---
- name: Set node runlists
  tags:
  - nodes
  - runlist
  command: knife node run_list add {{item.0}} {{item.1}}
  with_together:
    - groups.cluster
    - chef_runlists
  changed_when: False # Can't tell when this changed
