---
- name: Setup .ssh
  tags: keys
  file: dest={{ansible_env.HOME}}/.ssh mode=0700 state=directory
 
- name: Upload SSH keys
  tags: keys
  copy: src={{item|basename}} dest={{ansible_env.HOME}}/.ssh/{{item|basename}} mode=0600
  with_fileglob: id_*
 
- name: Trust keys
  tags: keys
  lineinfile:
    dest: "{{ansible_env.HOME}}/.ssh/authorized_keys"
    regexp: "^ssh-rsa.*root@ansible"
    line: "{{lookup('file', item)}}"
    state: present
  with_fileglob: id_*.pub

- name: Updating packages
  tags: packages
  yum: name=* state=latest
  when: ansible_os_family == "RedHat"

- name: Install python-apt if missing
  tags: packages
  command: apt-get -y install python-apt
  when: ansible_os_family == "Debian"

- name: Updating packages
  tags: packages
  apt: update_cache=yes upgrade=dist
  when: ansible_os_family == "Debian"

- name: Disable postfix
  tags: services
  service: name=postfix state=stopped enabled=no
  when: ansible_os_family == "RedHat"

- name: Clear existing cluster hosts
  tags: hosts
  host: hostname={{inventory_hostname}} state=absent
  register: result
  until: not result.changed
  retries: 10
  delay: 0
 
- name: Add cluster hosts svc nets
  tags: hosts
  host: hostname={{item}} ip={{hostvars[item].ifaces.svc.ipv4}} state=present
  when: "'svc' in hostvars[item].ifaces"
  with_items: groups.hosts
 
- name: Configure network interfaces
  tags: networks
  template: src=ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{item.iface}}
  when: item.iface in ansible_interfaces and ansible_os_family == "RedHat"
  with_items: ifaces.values()
  changed_when: True
  notify:
  - Down interfaces
  - Up interfaces
  - Ping addresses

- name: Configure network interfaces
  tags: networks
  lineinfile:
    dest: /etc/network/interfaces
    regexp: ^auto {{item.iface}}
    insertafter: ^auto {{item.iface}}
    line: "iface {{item.iface}} inet manual\n    address {{item.ipv4}}\n    netmask {{item.mask}}"
  when: item.iface in ansible_interfaces and ansible_os_family == "Debian"
  with_items: ifaces.values()
  notify:
  - Down interfaces
  - Up interfaces
  - Ping addresses
