---
# Replace with python 2.x more explicitly
ansible_python_interpreter: /usr/bin/python2

# Root ahoy!
ansible_ssh_user: root

# pyrax format creds file
rax_creds: rax_creds

# Datacenter region
rax_region: IAD

# The keypair must already exist
rax_keypair: jenkins

# Ubuntu image
rax_image: c3153cde-2d23-4186-b7da-159adbe2858b

# Manual for the fastness
rax_diskconfig: manual

host_prefix: "{{lookup('env', 'BUILD_PREFIX')}}-{{lookup('env', 'BUILD_NUMBER')}}"

# Cloud Networks to attach
rax_net_labels:
- public
- private
- "{{host_prefix}}-svc"
- "{{host_prefix}}-iso"

# Cloud networks to ensure
rax_net_info:
- label: "{{host_prefix}}-svc"
  cidr: 172.20.0.0/24
- label: "{{host_prefix}}-iso"
  cidr: 172.30.0.0/24
