---
ansible_ssh_user: root
rax_creds: rax_creds
rax_region: IAD
rax_keypair: evan
#rax_flavor: 5
rax_flavor: performance1-4
# CentOS 6.4
rax_image: f70ed7c7-b42e-4d77-83d8-40fa29825b85
# Ubuntu Precise 12.04.3
#rax_image: c3153cde-2d23-4186-b7da-159adbe2858b
rax_diskconfig: manual
rax_networks:
  - {name: public}
  - {name: private}
  # CS seems to add isolated networks in reverse order
#  - {name: apsu-ha-iso, cidr: 172.20.1.0/24}
  - {name: apsu-ha-svc, cidr: 172.20.0.0/24}
